on: 
  push:
    branches:
      - style
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
      
    - name: 🔨 Build Project
      run: |
        cd plugins/cuberaksi-sundara/woo/templates/myaccount/react
        npm install
        npm run build

    - name: 📂 Sync files theme
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 45.130.228.156
        username: u822946699.sundara
        password: Secret123!
        local-dir: ./themes/sundara-theme/
        server-dir: ./wp-content/themes/sundara-theme/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**

    - name: 📂 Sync files plugin cuberaksi-sundara
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 45.130.228.156
        username: u822946699.sundara
        password: Secret123!
        local-dir: ./plugins/cuberaksi-sundara/
        server-dir: ./wp-content/plugins/cuberaksi-sundara/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          


   